---
- name: Reboot host
  hosts: all
  become: true
  tasks:
    - name: Start reboot
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible. Reason: Semaphore playbook"
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
      become: true

    - name: Check uptime
      ansible.builtin.shell: "uptime"
      register: Uptime

    - ansible.builtin.debug: var=Uptime.stdout
