---
---
- name: Debug devices
  hosts: all
  become: true
  tasks:
    - name: Debug device links
      ansible.builtin.debug:
        var: ansible_device_links

    - name: "Debug devices"
      ansible.builtin.debug:
        var: ansible_devices
